
import java.awt.Color;
import java.awt.Toolkit;
import java.awt.event.KeyEvent;
import java.awt.event.WindowEvent;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author king
 */
public class snapdeal_login_page extends javax.swing.JFrame {

    /**
     * Creates new form snapdeal_login_page
     */
    public snapdeal_login_page() {
      
        initComponents();
      this.setResizable(false);
        this.setTitle("Login");
    this.setSize(800,500);
        this.getContentPane().setBackground(Color.WHITE);
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        username = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        password = new javax.swing.JPasswordField();
        jCheckBox2 = new javax.swing.JCheckBox();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Login to your snapdeal account");
        getContentPane().setLayout(null);

        jPanel2.setLayout(null);

        username.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        username.setToolTipText("enter your email id");
        jPanel2.add(username);
        username.setBounds(480, 80, 250, 30);

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Project Pictures/snapdeal login.PNG"))); // NOI18N
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton1);
        jButton1.setBounds(490, 200, 260, 30);

        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Project Pictures/snapdeal login with google.PNG"))); // NOI18N
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton2);
        jButton2.setBounds(570, 280, 120, 30);

        password.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        password.setToolTipText("enter your password");
        password.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                passwordKeyPressed(evt);
            }
        });
        jPanel2.add(password);
        password.setBounds(480, 130, 250, 30);

        jCheckBox2.setText("show password");
        jCheckBox2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox2ActionPerformed(evt);
            }
        });
        jPanel2.add(jCheckBox2);
        jCheckBox2.setBounds(480, 160, 180, 23);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Project Pictures/snapdeal_login_background.jpg"))); // NOI18N
        jPanel2.add(jLabel1);
        jLabel1.setBounds(0, 0, 770, 460);

        getContentPane().add(jPanel2);
        jPanel2.setBounds(0, 0, 770, 460);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jCheckBox2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox2ActionPerformed
if(jCheckBox2.isSelected())
    password.setEchoChar((char)0);
else
    password.setEchoChar('*');
// TODO add your handling code here:
    }//GEN-LAST:event_jCheckBox2ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
close();
Login_frame lf=new Login_frame();
lf.setVisible(true);
// TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
try
{
    String email=username.getText();
    String i_pass=password.getText();
    Class.forName("java.sql.DriverManager");
   Connection c=(Connection)
           DriverManager.getConnection("jdbc:mysql://localhost:3306/gmail","root","12345");
   Statement s=(Statement) c.createStatement();
   String q="SELECT first_name,alt_email,password FROM createaccount WHERE alt_email='"+email+"';";
   ResultSet r=s.executeQuery(q);
   
   int i=1;
   while (r.next())
   {
       String o_email=r.getString("alt_email");
       String pass=r.getString("password");
       String name=r.getString("first_name").toUpperCase();
       String seller="seller@gmail.com";
       if(o_email.equals(email) && pass.equals(i_pass))
       {
           if(o_email.equals(seller))
           {
               JOptionPane.showMessageDialog(this,"Logged in as Seller !");
               close();
               seller_mobile sp=new seller_mobile();
               sp.setVisible(true);
           }
           else
     {
       JOptionPane.showMessageDialog(this,"WELCOME "+name);
       close();
       snapdeal_main_page smp=new snapdeal_main_page();
       smp.hidden_email.setText(this.username.getText());
       snapdeal_main_page.jLabel2.setText(name);

       smp.setVisible(true);
       }
     }
       else 
           JOptionPane.showMessageDialog(this,"Incorrect Password");
       password.setText("");
       
       i++;
   }
   if(i==1)
       JOptionPane.showMessageDialog(this,"Incorrect Username/password");
   password.setText("");
   username.setText("");
}
catch(Exception e)
{
    JOptionPane.showMessageDialog(this,e.getMessage());
}
    

    }//GEN-LAST:event_jButton1ActionPerformed

    private void passwordKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_passwordKeyPressed
if(evt.getKeyCode()==KeyEvent.VK_ENTER)
{
    jButton1.doClick();
}
    }//GEN-LAST:event_passwordKeyPressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(snapdeal_login_page.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(snapdeal_login_page.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(snapdeal_login_page.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(snapdeal_login_page.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new snapdeal_login_page().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JCheckBox jCheckBox2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPasswordField password;
    private javax.swing.JTextField username;
    // End of variables declaration//GEN-END:variables

    private void close() {
         WindowEvent winc=new WindowEvent(this,WindowEvent.WINDOW_CLOSING);
        Toolkit.getDefaultToolkit().getSystemEventQueue().postEvent(winc); //To change body of generated methods, choose Tools | Templates.
    }
}
